---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - cf97ced6498fa6be365c796f5da0b64b
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    channel: "eslint-3"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/